# Open text/code files in Neovim in a new Kitty tab
protocol file
mime text/*
action launch --type=tab --cwd=current nvim ${FILE_PATH}

protocol file
ext ts,tsx,js,jsx,json,css,html,lua,md,yml,yaml,toml,conf,cfg,sh,bash,zsh,py,rb,go,rs,c,h,cpp,hpp,java,xml,svg,env,gitignore,dockerignore,prisma,graphql,sql
action launch --type=tab --cwd=current nvim ${FILE_PATH}
